namespace AJ.Terminal.Classes;

internal static class Words
{
    public static IReadOnlyList<string> wordSort = ["ABSOLUTE", "ACADEMIC", "ACCURACY", "ACTIVATE", "ADAPTER", "ADVANCED", "AIRCRAFT", "ALGORITHM", "ANALYZER", "APPROVAL",
"ARCHIVES", "ASSEMBLY", "ATTACKER", "AUTOMATE", "BACKDOOR", "BACKPACK", "BASELINE", "BIOLOGIC", "BLUEPRINT", "BOOTABLE",
"BREAKING", "BROADCAST", "BUILDING", "CALCULUS", "CAMPAIGN", "CAPACITY", "CATALOGS", "CHECKSUM", "CHEMICAL", "CIRCUITS",
"CLASSIFY", "COMPILER", "COMPUTER", "CONSOLES", "CONSTANT", "CONTROLS", "DATABASE", "DEBUGGER", "DECODING", "DELIVERY",
"DETECTED", "DIAGRAMS", "DIRECTED", "DISCOVER", "DISTANCE", "DOCUMENT", "DOWNLOAD", "ELEVATOR", "EMERGENCY", "ENCODING",
"ENCRYPTS", "ENGINEER", "ESTIMATE", "EXECUTOR", "EXTERNAL", "FACILITY", "FILENAME", "FIREWALL", "FIRMWARE", "FUNCTION",
"GENERATE", "GRAPHICS", "HARDWARE", "IDENTIFY", "INCOMING", "INSTANCE", "INTERNET", "KEYBOARD", "LANGUAGE", "LOCATION",
"MECHANIC", "MEMORIES", "MESSAGES", "MISSIONS", "MONITORS", "MOUNTAIN", "NETWORKS", "NOTEBOOK", "NUMERICAL", "OPERATOR",
"OUTGOING", "PASSWORD", "PIPELINE", "POSITION", "POWERFUL", "PRIORITY", "PROCESSOR", "PROTOCOL", "QUESTION", "RADIATOR",
"REACTION", "RECOVERY", "REGISTER", "RELIABLE", "RESOURCE", "RETRIEVE", "SCANNING", "SECURITY", "SEQUENCE", "SOFTWARE",
"STANDARD", "STARTING", "STORAGE", "STRATEGY", "SURVIVAL", "SWITCHES", "TERMINAL", "TRANSFER", "UNLOCKED", "VARIABLE"];

}